<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.20.osoe-925" />

  <PropertyGroup>
    <Title>Lombiq Audit Trail Extensions for Orchard Core</Title>
    <CopyrightYear>2021</CopyrightYear>
    <DescriptionBody>A module with additional features for the Audit Trail module in Orchard Core.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;AuditTrail</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Audit-Trail-Extensions</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.AuditTrail" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Contents" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.20.osoe-925" />
</Project>
